# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('player',),
            },
        ),
        migrations.CreateModel(
            name='BundleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('power', models.IntegerField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CardForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='new card form', max_length=100)),
                ('num_levels', models.IntegerField(default=0)),
                ('form_sequence', models.IntegerField(default=0)),
                ('image', models.URLField(default='')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardsGame.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Concret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ConcretCard',
            fields=[
                ('concret_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cardsGame.Concret')),
                ('locked', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardsGame.CardForm')),
            ],
            bases=('cardsGame.concret',),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardsGame.User'),
        ),
        migrations.AddField(
            model_name='concret',
            name='bundle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cardsGame.Bundle'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardsGame.Player'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cardsGame.BundleType'),
        ),
    ]
