# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsGame', '0003_auto_20160208_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
