# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsGame', '0004_auto_20160208_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
